server:
  port: 8082

bot:
  token: 7229980045:AAFp3IlUV0uzaONiXY0IXj_Y1a9iR_lkin4

service:
  mail:
    uri: http://127.0.0.1:8087/mail/send

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: xwstxkx
    password: 123321
  datasource:
    url: jdbc:postgresql://localhost:5432/projectdb
    username: xwstx
    password: Oid23UUzwAlf
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update