server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projectdb
    username: xwstx
    password: Oid23UUzwAlf
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update


selenium:
  webSiteUrl:
    https://ch.info-center.by/
  dateUrl:
    //input[@placeholder='Выберите дату']
  switchUrl:
    //div[@class='air-datepicker-nav--action']
  dateClickUrl:
    //div[@class='air-datepicker-nav--title']
  yearUrl:
    //div[@class='air-datepicker-nav--title']
  uidUrl:
    //div[@class='qr-inp']//input[@class='_required']
  buttonUrl:
    (//button[@form='check1'])[1]
  checkUrl:
    //div[@class='check-full__total-main']//span[2]
  browserName:
    chrome
  hubUrl:
    http://localhost:4444/wd/hub

