server:
  port: 8081

spring:
  application:
    name: kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer:
      value-deserializer:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer:
      value-serializer:
    bootstrap-servers: localhost:9092
