server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: xwstxkx
    password: 123321
  datasource:
    url: jdbc:postgresql://localhost:5432/projectdb
    username: xwstx
    password: Oid23UUzwAlf
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update